#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go dbGestionContacts $@
fi


if [ "$1" = "purge" ]; then
	rm -f /etc/dbGestionContacts/debian-db.php
	if which ucf >/dev/null 2>&1; then
		ucf --purge /etc/dbGestionContacts/debian-db.php
		ucfr --purge dbGestionContacts /etc/dbGestionContacts/debian-db.php
	fi
fi

#DEBHELPER#
